FROM debian:buster
LABEL maintainer="ji-park@student.42seoul.kr"

RUN apt-get update && apt-get install -y \
    openssl \ 
    wget \
    nginx \ 
    vim \
    php7.3-fpm \
    mariadb-server \
    php-mysql \
    php-mbstring

COPY    ./srcs/default ./
COPY    ./srcs/run.sh ./
COPY    ./srcs/DB.sql ./
COPY    ./srcs/wp-config.php ./
COPY    ./srcs/config.inc.php ./

EXPOSE 80 433

CMD bash run.sh

